version: '3'
services:
  python3.10:
    restart: always
    build: .
    container_name: 'python3.10.2'
    working_dir: '/Pyexam2'
    tty: true
    volumes:
      - ./logs:/Pyexam2/logs
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    container_name: es01
    environment:
      - "discovery.type=single-nood"
    ports:
      - 9200:9200
    networks:
      - elastic
kib01:
  image: docker.elastic.co/kibana/kibana:8.1.0
  container_name: kib01
  ports:
    - 5601:5601
  environment:
    ELASTICSEARCH_URL: http://es01:9200
  networks:
    - elastic

volumes:
  data01:
    driver: loacal
networks:
  elastic:
    driver: bridge